services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Pfad zum Dockerfile im src-Verzeichnis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/bookNowDB.sqlite
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build:
      context: react/book-now
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  # postgresdb:
    #  image: postgres:latest
    # restart: always
    # environment:
      #  POSTGRES_DB: bookNowDB
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres

